### ISSUE TITLE
Where did the method **getitem_dataclass** go?

### ISSUE THREAD

**Issue by sambaPython24** [tum-pbs/PhiML#9]
When I try to use the module ```phi.flow``, it tries to import the phiml module but I get the error message 
```
ImportError: cannot import name 'getitem_dataclass' from 'phiml.math._magic_ops' (.../phiml/math/_magic_ops.py)
```

I canot find that class in this code. Has it been removed or renamed? Do you know how to resolve this error?

**Comment by Dominic-DallOsto** [comment]
I get the same error with phiml 1.12.0 and 1.11.0 but it works with 1.10.0

```python
      5 from phiml import math
      6 from phiml.math import (Shape, dual, wrap, Tensor, expand, vec, where, ncat, clip, length, normalize, minimum, vec_squared, channel, instance, stack, maximum, PI, linspace, sin, cos, sqrt, batch)
----> 7 from phiml.math._magic_ops import all_attributes, getitem_dataclass
      8 from ._geom import Geometry
      9 from ._transform import rotate, rotation_matrix, rotation_matrix_from_directions, rotation_angles

ImportError: cannot import name 'getitem_dataclass' from 'phiml.math._magic_ops' (.../python3.12/site-packages/phiml/math/_magic_ops.py)
```

**Comment by Dominic-DallOsto** [comment]
See https://github.com/tum-pbs/PhiML/commit/048f6e5ca7074684738faa6261504e1f5d343595#diff-ee7e29ff00dc47aef3f96c2f94e4a2220e3b8cefdcf37856b0e64968fc29321e
